# Generated by Django 4.2.16 on 2026-05-18 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du district')),
                ('code_geojson', models.CharField(blank=True, help_text="Correspond à la propriété 'district_id' dans le GeoJSON", max_length=50, verbose_name='Identifiant GeoJSON')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Population (dernière valeur connue)')),
            ],
            options={
                'verbose_name': 'District sanitaire',
                'verbose_name_plural': 'Districts sanitaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithme', models.CharField(max_length=5, verbose_name='Algorithme')),
                ('fold', models.PositiveSmallIntegerField(verbose_name='Pli walk-forward (1-5)')),
                ('horizon', models.PositiveSmallIntegerField(verbose_name='Horizon (mois)')),
                ('rmse', models.FloatField(verbose_name='RMSE')),
                ('mae', models.FloatField(verbose_name='MAE')),
                ('r2', models.FloatField(verbose_name='R²')),
                ('n_predictions', models.PositiveIntegerField(default=0, verbose_name='Nombre de prédictions')),
            ],
            options={
                'verbose_name': 'Performance modèle',
                'verbose_name_plural': 'Performances modèles',
                'ordering': ['algorithme', 'fold', 'horizon'],
                'unique_together': {('algorithme', 'fold', 'horizon')},
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'import")),
                ('fichier_nom', models.CharField(blank=True, max_length=255, verbose_name='Fichier')),
                ('nb_lignes', models.PositiveIntegerField(default=0, verbose_name='Nombre de lignes')),
                ('nb_districts', models.PositiveIntegerField(default=0, verbose_name='Districts couverts')),
                ('periode', models.CharField(blank=True, max_length=50, verbose_name='Période (YYYY-MM)')),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('erreur', 'Erreur'), ('partiel', 'Partiel')], default='succes', max_length=10)),
                ('message', models.TextField(blank=True, verbose_name='Détails')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal des imports',
                'verbose_name_plural': 'Journaux des imports',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='SeuilAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_calendaire', models.PositiveSmallIntegerField(verbose_name='Mois calendaire (1-12)')),
                ('p25', models.FloatField(verbose_name='Percentile 25')),
                ('p75', models.FloatField(verbose_name='Percentile 75 (seuil orange)')),
                ('p90', models.FloatField(verbose_name='Percentile 90 (seuil rouge)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': "Seuil d'alerte",
                'verbose_name_plural': "Seuils d'alerte",
                'ordering': ['district', 'mois_calendaire'],
                'unique_together': {('district', 'mois_calendaire')},
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithme', models.CharField(choices=[('RF', 'Random Forest'), ('XGB', 'XGBoost')], max_length=5, verbose_name='Algorithme')),
                ('horizon', models.PositiveSmallIntegerField(verbose_name='Horizon (mois)')),
                ('date_origine', models.DateField(verbose_name="Date d'origine de la prévision")),
                ('date_cible', models.DateField(verbose_name='Date cible')),
                ('incidence_predite', models.FloatField(verbose_name='Incidence prédite (/1000)')),
                ('cas_predits', models.FloatField(verbose_name='Cas prédits')),
                ('niveau_alerte', models.CharField(choices=[('vert', 'Normal'), ('orange', 'Élevé'), ('rouge', 'Critique')], default='vert', max_length=10, verbose_name="Niveau d'alerte")),
                ('seuil_p75', models.FloatField(blank=True, null=True, verbose_name='Seuil P75')),
                ('seuil_p90', models.FloatField(blank=True, null=True, verbose_name='Seuil P90')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de calcul')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Prévision',
                'verbose_name_plural': 'Prévisions',
                'ordering': ['-date_origine', 'district', 'algorithme', 'horizon'],
                'indexes': [models.Index(fields=['date_origine', 'algorithme'], name='core_previs_date_or_7e2725_idx'), models.Index(fields=['niveau_alerte'], name='core_previs_niveau__7c2c2a_idx')],
                'unique_together': {('district', 'algorithme', 'horizon', 'date_origine')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Mois (1er jour du mois)')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('trimestre', models.CharField(blank=True, max_length=2, verbose_name='Trimestre')),
                ('cas_confirmes', models.FloatField(verbose_name='Cas confirmés')),
                ('population', models.PositiveIntegerField(verbose_name='Population')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Observation mensuelle',
                'verbose_name_plural': 'Observations mensuelles',
                'ordering': ['district', 'date'],
                'indexes': [models.Index(fields=['district', 'date'], name='core_observ_distric_afaec9_idx'), models.Index(fields=['annee', 'mois'], name='core_observ_annee_2781ca_idx')],
                'unique_together': {('district', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Mois')),
                ('temp_moy', models.FloatField(verbose_name='Température moyenne (°C)')),
                ('humidite', models.FloatField(verbose_name='Humidité relative (%)')),
                ('precip_mensuel', models.FloatField(verbose_name='Précipitations mensuelles (mm)')),
                ('source', models.CharField(default='NASA_POWER', max_length=50, verbose_name='Source de la donnée')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteos', to='core.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Donnée climatique',
                'verbose_name_plural': 'Données climatiques',
                'ordering': ['district', 'date'],
                'unique_together': {('district', 'date')},
            },
        ),
    ]
