# Generated by Django 4.2.16 on 2026-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuilalerte',
            name='ecart_type',
            field=models.FloatField(default=0, verbose_name='Écart-type historique'),
        ),
        migrations.AddField(
            model_name='seuilalerte',
            name='moyenne',
            field=models.FloatField(default=0, verbose_name='Moyenne historique'),
        ),
        migrations.AddField(
            model_name='seuilalerte',
            name='seuil_alerte',
            field=models.FloatField(default=0, verbose_name="Seuil d'alerte (M + σ)"),
        ),
        migrations.AddField(
            model_name='seuilalerte',
            name='seuil_epidemio',
            field=models.FloatField(default=0, verbose_name='Seuil épidémiologique (M + 2σ)'),
        ),
        migrations.AlterField(
            model_name='seuilalerte',
            name='p25',
            field=models.FloatField(default=0, verbose_name='[deprecated] Percentile 25'),
        ),
        migrations.AlterField(
            model_name='seuilalerte',
            name='p75',
            field=models.FloatField(default=0, verbose_name='[deprecated] Percentile 75'),
        ),
        migrations.AlterField(
            model_name='seuilalerte',
            name='p90',
            field=models.FloatField(default=0, verbose_name='[deprecated] Percentile 90'),
        ),
    ]
