# Generated by Django 4.2.16 on 2026-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seuils_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevision',
            name='algorithme',
            field=models.CharField(choices=[('RF', 'Random Forest'), ('XGB', 'XGBoost'), ('META', 'Méta-modèle adaptatif (Ridge h=1 + XGBoost h=2/3)')], max_length=5, verbose_name='Algorithme'),
        ),
    ]
